### PR TITLE
Add DistributeRel Message

### PR DESCRIPTION
**Pull request by ZJie1**

### CODE REVIEW

**Comment by ZJie1** [comment]
@jacques-n @cpcloud  could you please help review this?

**Comment by jacques-n** [comment]
@ZJie1, will do soon, sorry for the delay!

**Comment by jacques-n** [comment]
Opened a conversation about this in Slack: https://substrait.slack.com/archives/C02D7CTQXHD/p1642457381001600

**Comment by jacques-n** [comment]
Any opinions from people on the proposal I made on Slack?

**Comment by ZJie1** [comment]
> Any opinions from people on the proposal I made on Slack?

haven't see other people's replies @Ferdinand Xu @Xin Dong can you help on this?

**Comment by jacques-n** [comment]
Closing as it was superseded by #142.

**Pull request closed without merging**
