### PR TITLE
feat: make substrait repo a go module

### PR DESCRIPTION
**Pull request by anshuldata**
This facilitates substrait assets use in go projects

### CODE REVIEW

**Review by jacques-n — DISMISSED** [review]
Looks good to me. Have you confirmed that you can use this in substrait-go? I believe you can do a `go get` against your fork+hash somehow and test.

**Comment by zeroshade** [comment]
You can use a `replace` directive in the go.mod locally to point it at this branch. If you need I can provide the exact commands tomorrow via go mod edit to help out.

**Comment by anshuldata** [comment]
> Looks good to me. Have you confirmed that you can use this in substrait-go? I believe you can do a `go get` against your fork+hash somehow and test.

yes, I confirmed by creating a module which has same go.mod and core.go and accessing that referring this module in substrait-go. "go get" gets to local cache and pushes to go package repository too

Screenshot 2024-09-27 at 10 56 46 AM

**Comment by anshuldata** [comment]
> You can use a `replace` directive in the go.mod locally to point it at this branch. If you need I can provide the exact commands tomorrow via go mod edit to help out.

yes, I tested it using "replace" directive to locally point to this repo

**Comment by jacques-n** [comment]
@zeroshade , look good to you?

**Review by zeroshade — APPROVED** [review]
It might be worth adding a small test for this? But otherwise this seems fine to me.

It also might be worthwhile adding a package level comment and maybe a testable example showing how to use the FS?

**Comment by jacques-n** [comment]
Comment seems useful. I'm inclined to avoid adding any tests/extra stuff here. Really figure people will primarily use via substrait-go as opposed to direct.

**Comment by anshuldata** [comment]
> It also might be worthwhile adding a package level comment and maybe a testable example showing how to use the FS?
Added comment

> I'm inclined to avoid adding any tests/extra stuff here
I have skipped adding test case

**Review by zeroshade — APPROVED** [review]

**Pull request merged**
