### PR TITLE
docs: add governance doc to site

### PR DESCRIPTION
**Pull request by mbrobbel**
Copies and converts the approved governance doc to markdown, I added some links and added a plugin that generates a table based on two yaml files with the project roster.

### CODE REVIEW

**Comment by jacques-n** [comment]
This looks good to me. Thanks for doing this @mbrobbel !

I didn't actually review the content to confirm it matches 1:1 but I'm going to assume it does. You okay with that @westonpace ?

**Review by gforsyth — APPROVED** [review]
This looks good to me and I've done a human-based diff between this and https://docs.google.com/document/d/1iMI7oInk5ND5jYEzX6-ljo54fPgdKvhQPFtIc1jeRoQ and it matches.

**Review by westonpace — APPROVED** [review]
Looks like a good conversion to me.  Thanks for the effort!  I don't want to merge as I'm on mobile (on a trip at the moment) so if anyone else wants to then go for it!

**Comment by gforsyth** [comment]
Thanks, @mbrobbel !

**Pull request merged**
