### PR TITLE
feat: add population option to variance and standard deviation functions

### PR DESCRIPTION
**Pull request by vibhatha**
In this PR population variance and standard-deviation is added.

BREAKING CHANGE: signature change of `variance` and `std_dev`

### CODE REVIEW

**Comment by gforsyth** [comment]
hmm, I wonder if `population` vs `sample` should be options to pass to the `variance` and `std-dev` functions (with a default of `sample`).
I don't think they need to be separate functions.

**Comment by gforsyth** [comment]
And I know `postgres` defaults to `population` for things like `variance` but that doesn't make very much sense to me

**Comment by vibhatha** [comment]
@gforsyth I added an option to choose the `distribution`.

**Comment by jvanstraten** [comment]
To be perfectly honest, I have no idea what the difference is, so I have no opinion on the matter. But if you believe that there's no sane default for this, you can also just make the enum required, to force the producer to pick which option they want.

**Comment by gforsyth** [comment]
`sample` is the sane default

**Review by jvanstraten — APPROVED** [review]
LGTM then.

**Comment by vibhatha** [comment]
@jvanstraten any changes required?

**Review by jvanstraten — APPROVED** [review]
I guess your merge/rebase dismissed my previous approval.

**Comment by jvanstraten** [comment]
Needs rebase due to previous merges.

**Comment by vibhatha** [comment]
@jvanstraten I updated, I think the approval vanishes after pushing.

**Review by jvanstraten — APPROVED** [review]

**Pull request merged**
