### PR TITLE
Use markdown extension to embed protobuf IDL in docs

### LINKED ISSUE #26: Create a way to embed associated protobuf/human readable/etc IDL in documentation pages.
We should define a way to embed the relative portions of serialization and examples in the specification pages to help people understand how things are expressed.

### PR DESCRIPTION
**Pull request by rymurr**
This adds the [mkdocs-protobuf](https://github.com/rymurr/mkdocs-protobuf) extension to the site and adds one protobuf message to the documetnation.

I have just done one as an example of a few ways we might add protobuf definitions:
1) just simply add with a statement like "this is the binary representation"
2) tabbed view which shows the protobuf IDL for a message, the human readable version and an example.

Before making a lot of changes I thought I would see what everyone else thought.

Fixes #26

---
This change is [Reviewable](https://reviewable.io/reviews/substrait-io/substrait/36)

### CODE REVIEW

**Comment by jacques-n** [comment]
Ok, maybe I'm doing something foolish but when I try to run mkdocs serve on this PR I get the message below. Seems like it is choking on parsing the proto file?

```
% mkdocs serve
INFO     -  Building documentation...
Traceback (most recent call last):
  File "/Users/jnadeau/src/substrait/site/venv/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/Users/jnadeau/src/substrait/site/venv/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jnadeau/src/substrait/site/venv/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/jnadeau/src/substrait/site/venv/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jnadeau/src/substrait/site/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jnadeau/src/substrait/site/venv/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/jnadeau/src/substrait/site/venv/lib/python3.8/site-packages/mkdocs/__main__.py", line 173, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, **kwargs)
  File "/Users/jnadeau/src/substrait/site/venv/lib/python3.8/site-packages/mkdocs/commands/serve.py", line 54, in serve
    config = builder()
  File "/Users/jnadeau/src/substrait/site/venv/lib/python3.8/site-packages/mkdocs/commands/serve.py", line 49, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/Users/jnadeau/src/substrait/site/venv/lib/python3.8/site-packages/mkdocs/commands/build.py", line 252, in build
    config['plugins'].run_event('pre_build', config=config)
  File "/Users/jnadeau/src/substrait/site/venv/lib/python3.8/site-packages/mkdocs/plugins.py", line 96, in run_event
    result = method(**kwargs)
  File "/Users/jnadeau/src/substrait/site/venv/lib/python3.8/site-packages/mkdocs_protobuf/plugin.py", line 36, in on_pre_build
    self.messages.update(read_proto(os.path.abspath(os.path.join(root, proto)), indent_depth))
  File "/Users/jnadeau/src/substrait/site/venv/lib/python3.8/site-packages/mkdocs_protobuf/plugin.py", line 67, in read_proto
    data = f.read()
  File "/usr/local/opt/python@3.8/bin/../Frameworks/Python.framework/Versions/3.8/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x86 in position 23: invalid start byte
```

**Comment by rymurr** [comment]
hrm...since it works on my machine and on the build i am assuming its an OSX issue. I double checked the files and there are no non-ascii characters in the proto files or any weird/invisible characters. The line endings also appear correct.

Can you add `print(proto)` to line 39 of "/Users/jnadeau/src/substrait/site/venv/lib/python3.8/site-packages/mkdocs_protobuf/plugin.py" so we can at least find out which file is the problem.

Would be curious of the output of `file -i` and `cat -A` would be on that file.

**Comment by rymurr** [comment]
ive updated the plugin to `0.0.8`. Let me know if it works now. Give pypi a few minutes to sync the plugin...looks like it hasnt' been uploaded yet

**Comment by jacques-n** [comment]
I confirmed locally that with 0.7, the problem was a `.DS_Store` file in the directory, something macos creates. The update fixed my problem. Are you now filtering to only certain list of file extensions or similar?

This last commit has your build failing with `No matching distribution found for mkdocs-protobuf==0.0.8`

**Review by jacques-n — APPROVED** [review]
This looks like a great start. I like the tabbed interface. Even though some is empty, it is good to indicate our intentions. Want to follow up with additions elsewhere?

**Pull request merged**
