### PR TITLE
ci: remove breaking change detection

### PR DESCRIPTION
**Pull request by cpcloud**
This PR removes the buf breaking change detection until we hit 1.0.

### CODE REVIEW

**Comment by cpcloud** [comment]
cc @westonpace @jvanstraten @jacques-n

Was thinking we should disable this until 1.0, so that we don't have to trigger a major release while we're still iterating towards 1.0.

**Review by westonpace — DISMISSED** [review]
Agreed.  Though I think, instead of disabling breaking change, we change it to require "feature" classification (e.g. bump the minor version).  This matches the semantic versioning scheme for 0.x releases.

**Comment by cpcloud** [comment]
That makes sense.

**Comment by jacques-n** [comment]
I'm -1 on disabling the breaking commit comment check. I think we should be deliberate about overriding. Having a failing precommit that we decide to override is better than accidentally introducing breaking changes when we didn't mean to. That being said... 

I think I'll start a thread on the mailing list. I don't think we should make 1.0 a thing. It's just a number and I don't see a great reason to have a different system before vs after. 

And if we do want to make 1.0 a thing, I think we should still document breaking changes as breaking even if we don't bump major version until later... Introducing a breaking change but not telling people in the release notes is a bad outcome from my pov.

**Comment by westonpace** [comment]
+1 for hashing it out on the ML.

**Comment by jvanstraten** [comment]
+1 for ML thread, but pending that, I guess +/-0 for this PR. I always thought that for 0.x.y x++ means breaking and y++ means anything else, but apparently semver [makes no assertions about that](https://semver.org/spec/v2.0.0.html#spec-item-4). TIL.

**Comment by cpcloud** [comment]
Superseded by #210.

**Pull request closed without merging**
