### PR TITLE
run protoc for PRs

### LINKED ISSUE #20: Add a github workflow step that verifies correctness of the .proto files before merge
Right now, there is no pre-commit step that verifies the proto files are valid. We should add something that verifies this (even though we don't release any artifacts based on the proto files).

### PR DESCRIPTION
**Pull request by rymurr**
Fixes #20

---
This change is [Reviewable](https://reviewable.io/reviews/substrait-io/substrait/38)

### CODE REVIEW

**Comment by rymurr** [comment]
@jacques-n can you approve this workflow for me :-)

**Comment by jacques-n** [comment]
Can you post an invalid proto change so we can confirm build fails when it occurs? Hard to tell from output that protos are actually compiled. If it fails on bad proto, we can reverse the test and merge.

**Comment by rymurr** [comment]
build is failing w/ new proto msg

**Comment by jacques-n** [comment]
Cool, thanks

**Review by jacques-n — APPROVED** [review]
Looks good, thanks @rymurr

**Pull request merged**
