### PR TITLE
feat: add is distinct from function

### PR DESCRIPTION
**Pull request by JazabC**
PR to add `is distinct from` function

### CODE REVIEW

**Review by bvolpato — APPROVED** [review]
Given that the negation form exists (`is_not_distinct_from`), and that both are valid functions in Postgres and others (https://modern-sql.com/caniuse/is-distinct-from), I think this makes a lot of sense.

**Review by westonpace — APPROVED** [review]

**Comment by westonpace** [comment]
@richtia / @vibhatha care to take a look so we can have a second approval?

**Comment by vibhatha** [comment]
@westonpace sure, on it now.

**Review by vibhatha — APPROVED** [review]
Thanks for working on this, LGTM!

**Comment by vibhatha** [comment]
@westonpace Done!

**Comment by westonpace** [comment]
Thanks for the addition @JazabC!

**Pull request merged**
