### PR TITLE
docs: better explain aggregate relations

### PR DESCRIPTION
**Pull request by jvanstraten**
BREAKING CHANGE: the grouping set index column now only exists if there is more
than one grouping set.

### CODE REVIEW

**Comment by jvanstraten** [comment]
Closes #258

**Comment by jvanstraten** [comment]
Apparently buf is unable to build the protos within two minutes now...? FWIW I've also seen it be ridiculously slow on my machine.

**Comment by cpcloud** [comment]
The buf failure looked like an intermittent network problem, possibly related to https://github.com/bufbuild/buf/issues/824.

**Comment by jvanstraten** [comment]
It was hanging on the `buf generate` call though, so unless it was still downloading dependencies by then I don't think that was the issue just now. Weird. Add it to the pile of protobuf-related issues I suppose :man_shrugging:

**Review by jacques-n — APPROVED** [review]
Thanks!

**Pull request merged**
