### PR TITLE
docs: clarify result of sum() aggregate for zero elements

### PR DESCRIPTION
**Pull request by jvanstraten**

### CODE REVIEW

**Review by jacques-n — APPROVED** [review]

**Comment by julianhyde** [comment]
It's good to clarify what the behavior is, so I have no argument with this PR.

And I will note that this behavior is consistent with SQL's `SUM` aggregate function.

Still, there is a good argument that `sum()` should return zero, not null, for zero elements. Or that there should be another function `sum0` with that behavior. It easier to compute (because less internal state is required). It is easier to consume (because the caller doesn't have to deal with nulls). And anyone who wants the SQL-like behavior can write `case count(x) when 0 then null else sum0(x) end`. In Calcite we find `SUM0` to be a more useful primitive, and `SUM` is derived, like `AVG`.

**Comment by jvanstraten** [comment]
See #259; adding `sum0` as well is planned.

**Comment by julianhyde** [comment]
Good to hear. Sorry I didn't notice #255 and #259 earlier.

FWIW, you made some remarks in another case about the need for additive and multiplicative identities. I agree that identities are useful. But it wasn't totally clear whether you were thinking of NULL the additive identity. I have given a lot of thought to the algebraic aspects of SQL and I think it is wrong to think of NULL as an identity. Most SQL aggregate functions, `SUM` included, do not even see input values that are NULL.

**Comment by jvanstraten** [comment]
I was talking about the mathematical identities, i.e. the x in x + y = y + x = y for addition. So, zero.

**Pull request merged**
